//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> Quyen { get; set; }
        public string TenNguoiNhap { get; set; }
        public int CMND { get; set; }
        public Nullable<int> Sdt { get; set; }
    }
}
