//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuVucDieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuVucDieuTri()
        {
            this.PhongDieuTris = new HashSet<PhongDieuTri>();
        }
    
        public int IDKhuVucDieuTri { get; set; }
        public string TenKhuVucDieuTri { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongDieuTri> PhongDieuTris { get; set; }
    }
}
