//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuDieuTri
    {
        public int IDLichSuDieuTri { get; set; }
        public Nullable<int> IDBenhNhan { get; set; }
        public Nullable<int> IDNguoiDieuTri { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string LichSuDieuTri1 { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual NguoiDieuTri NguoiDieuTri { get; set; }
    }
}
