//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyCovidModels : DbContext
    {
        public QuanLyCovidModels()
            : base("name=QuanLyCovidModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<KhuVucDieuTri> KhuVucDieuTris { get; set; }
        public virtual DbSet<LichSuDieuTri> LichSuDieuTris { get; set; }
        public virtual DbSet<NguoiDieuTri> NguoiDieuTris { get; set; }
        public virtual DbSet<PhongDieuTri> PhongDieuTris { get; set; }
    }
}
