//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDieuTri()
        {
            this.LichSuDieuTris = new HashSet<LichSuDieuTri>();
        }
    
        public int IDNguoiDieuTri { get; set; }
        public string TenNguoiDieuTri { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public int CMND { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDieuTri> LichSuDieuTris { get; set; }
    }
}
