//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hệ_thống_quản_lý_bệnh_nhân_covid_19
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongDieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongDieuTri()
        {
            this.BenhNhans = new HashSet<BenhNhan>();
        }
    
        public int IDPhongDieuTri { get; set; }
        public string TenPhongDieuTri { get; set; }
        public Nullable<int> IDKhuVucDieuTri { get; set; }
        public Nullable<int> SoLuongGiuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhNhan> BenhNhans { get; set; }
        public virtual KhuVucDieuTri KhuVucDieuTri { get; set; }
    }
}
